// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBK-X6aDN76SfxJJi1UiYOtMILK7aYAc30',
    appId: '1:95177033076:web:c6ce63bcfd82dbf0f35821',
    messagingSenderId: '95177033076',
    projectId: 'legacyhub-shirahsoft',
    authDomain: 'legacyhub-shirahsoft.firebaseapp.com',
    storageBucket: 'legacyhub-shirahsoft.firebasestorage.app',
    measurementId: 'G-E0NWX1VWTX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsocYV2b2OphkNOVABK50rUOB6E0HoqDQ',
    appId: '1:95177033076:android:2f7818d72c9505c1f35821',
    messagingSenderId: '95177033076',
    projectId: 'legacyhub-shirahsoft',
    storageBucket: 'legacyhub-shirahsoft.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEA0xGxxpTHa4svHJ53DVepPiuodgMWMk',
    appId: '1:95177033076:ios:adc6ccba1d8b12c8f35821',
    messagingSenderId: '95177033076',
    projectId: 'legacyhub-shirahsoft',
    storageBucket: 'legacyhub-shirahsoft.firebasestorage.app',
    iosBundleId: 'com.shirahsoft.legacyhub',
  );
}
